version: '3.5'

services:
  web-mvc:
    container_name: web-mvc-eshop
    build:
      context: .
      dockerfile: WebMvc/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.dotnet/https/CatalogApi-eshop.pfx
      - PurchaseUrl=Https://catalog-api-eshop
      - ASPNETCORE_HTTPS_PORT=44384
      - ASPNETCORE_URLS=https://+443;http://+80
      - CERTIFICATE_PATH=C:\tmp\
    ports:
      - "44384:443"
      - "44385:80"
    volumes:
      - C:/tmp/:/root/.dotnet/https
  catalog-api:
    container_name: catalog-api-eshop
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    networks:
      - playground_default
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=server=sqlserver-eshop;user id=sa;password=Pass@word123;database=Microsoft.eShopOnContainers.Services.CatalogDb;
      - PicBaseUrl=https://localhost:44323/api/v1/catalog/items/[0]/pic/  #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - EventBusConnection=rabbitmq-eshop
      - EventBusUserName=admin
      - EventBusPassword=Pass@word123
      - AzureStorageAccountName=
      - AzureStorageAccountKey=
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=
      - OrchestratorType=
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/catalog-api
      - ASPNETCORE_HTTPS_PORT=44323
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Cert/CatalogApi-eshop.pfx
      - CERTIFICATE_PATH=C:\tmp\
    ports:
      - "44322:80"
      - "44323:443"
  basket-api:
    container_name: basket-api-eshop
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=44376
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Cert/CatalogApi-eshop.pfx
      - CERTIFICATE_PATH=C:\tmp\
    ports:
      - "44376:443"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-eshop
    networks:
      - playground_default
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq-eshop
      - C:/tmp/:/root/.dotnet/https
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Pass@word123
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver-eshop
    volumes:
      - sqlserverdata:/var/opt/sqlserver-eshop
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word123
  seq:
    image: datalust/seq:latest
    container_name: seq-eshop
    volumes:
      - seqdata:/var/opt/seqdata-eshop
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
      - "5341:5341"
volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true
  seqdata:
      external: true
networks:
  playground_default:
    name: playground_default